# Generated by Django 4.1.7 on 2023-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Должно содержать 13 символов', max_length=13, null=True, verbose_name='ISBN книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Введите краткое описание книги', max_length=1000, null=True, verbose_name='Аннотация книги'),
        ),
    ]
